// Composite the recorded master clip into the final demo video.
//
// Reads out/beats.json (measured beat timestamps + zoom targets from the real
// take) and out/narration/durations.json (measured line lengths), then:
//  1. Video: cuts straight into a static crop for each zoom beat (prop-sheet,
//     morph, agent) and one animated punch-in ramp for the first (inline-edit)
//     — a continuous camera glide across four back-to-back zoom beats reads
//     busier than cutting between already-framed shots, so only the entry
//     ramp animates. Inserts a cloned freeze-hold across the agent/undo seam:
//     the agent beat's on-screen span is real-time-constrained (undo must
//     fire within ~1s of the card landing — see story.ts/record.ts) and is
//     far shorter than its narration line, so post stretches it by holding
//     the last frame until the line finishes.
//  2. Audio: places each beat's narration at its recorded start time, shifted
//     by the freeze-hold duration for every beat after the freeze point.
//  3. Muxes video + narration into the final MP4.
//
// Usage: bun run scripts/demo-video/compose.ts
const outDir = new URL("./out/", import.meta.url).pathname;
const narrationDir = `${outDir}narration/`;

type Zoom = { x: number; y: number; scale: number };
type Mark = { id: string; startMs: number; endMs: number; zoom?: Zoom };
type BeatsFile = {
  viewport: { width: number; height: number };
  videoPath: string;
  freeze: { atMs: number } | null;
  beats: Mark[];
};

const beatsFile: BeatsFile = await Bun.file(`${outDir}beats.json`).json();
const { durations }: { durations: Record<string, number> } = await Bun.file(
  `${narrationDir}durations.json`,
).json();

const run = async (cmd: string[]) => {
  const proc = Bun.spawn(cmd, { stdout: "pipe", stderr: "pipe" });
  const [code, stdout, stderr] = await Promise.all([
    proc.exited,
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
  ]);
  if (code !== 0) throw new Error(`${cmd[0]} failed:\n${stderr}`);
  return stdout;
};

const durationOf = async (file: string) =>
  parseFloat(
    await run([
      "ffprobe",
      "-v",
      "error",
      "-show_entries",
      "format=duration",
      "-of",
      "default=noprint_wrappers=1:nokey=1",
      file,
    ]),
  );

const mark = (id: string): Mark => {
  const m = beatsFile.beats.find((b) => b.id === id);
  if (!m)
    throw new Error(
      `No beat mark for "${id}" — was beats.json regenerated by record.ts?`,
    );
  return m;
};

for (const id of [
  "zero-chrome",
  "intent",
  "inline-edit",
  "prop-sheet",
  "morph",
  "agent",
  "undo",
  "outro",
]) {
  const wav = `${narrationDir}${id}.wav`;
  if (!(await Bun.file(wav).exists()))
    throw new Error(`Missing narration: ${wav} — run narrate.ts first`);
  if (!(id in durations))
    throw new Error(`Missing duration for "${id}" in durations.json`);
}

const videoDurationSec = await durationOf(beatsFile.videoPath);
const videoDurationMs = Math.round(videoDurationSec * 1000);
const { width: W, height: H } = beatsFile.viewport;
const FPS = 25;

const zeroChrome = mark("zero-chrome");
const intent = mark("intent");
const inlineEdit = mark("inline-edit");
const propSheet = mark("prop-sheet");
const morph = mark("morph");
const agent = mark("agent");
const undo = mark("undo");
const outro = mark("outro");

if (!inlineEdit.zoom || !propSheet.zoom || !morph.zoom || !agent.zoom) {
  throw new Error(
    "Expected zoom targets on inline-edit, prop-sheet, morph, and agent beats",
  );
}

// ── The agent/undo seam's real cut point ───────────────────────────────
// beats.json's timestamps are JS wall-clock (Date.now()-t0 in record.ts);
// the video's own PTS clock starts counting from whenever Playwright's
// recorder actually opens its first frame, which lags t0 by an unknown,
// non-zero amount. Every other beat has multi-second dwell, so that lag is
// invisible; the agent beat's true on-screen card window is only ~650ms
// wide, and beats.json's endMs (`agent.endMs`) landed ~200ms after the undo
// had already completed on screen — confirmed by frame-scanning
// out/04dfd05a556e0427bb7b17dad22fa497.webm at 50fps around this seam (see
// out/scan/ during investigation: card visible through t=36.69s, gone by
// t=36.71s). Re-verify this against beats.json's agent mark if record.ts
// ever produces a new take — it is NOT derived from beats.json on purpose,
// so a stale value fails loud via the bounds check below rather than
// silently reusing the wrong instant.
const AGENT_CARD_GONE_SEC = 36.7;
if (
  AGENT_CARD_GONE_SEC * 1000 < agent.startMs ||
  AGENT_CARD_GONE_SEC * 1000 > agent.endMs + 1000
) {
  throw new Error(
    `AGENT_CARD_GONE_SEC (${AGENT_CARD_GONE_SEC}s) is out of range for this take's ` +
      `agent mark [${agent.startMs}, ${agent.endMs}]ms — re-verify it against ` +
      `${beatsFile.videoPath} (see the comment above) before composing.`,
  );
}

// ── Freeze-hold sizing ────────────────────────────────────────────────
// Stretch the agent beat's screen time until its narration line finishes,
// plus a small landing buffer before the undo line picks up. This is a
// delta between two JS-clock marks, so the PTS lag above cancels out —
// only the absolute trim boundaries need the corrected timestamp.
const FREEZE_BUFFER_MS = 300;
const freezeInsertMs = agent.endMs; // == undo.startMs; the seam we're stretching
const freezeMs =
  Math.max(0, agent.startMs + durations.agent - freezeInsertMs) +
  FREEZE_BUFFER_MS;

console.log(
  `[compose] video ${videoDurationSec.toFixed(3)}s · freeze-hold ${freezeMs}ms at ${freezeInsertMs}ms · ` +
    `final ≈ ${((videoDurationMs + freezeMs) / 1000).toFixed(1)}s`,
);

// ── Video graph ─────────────────────────────────────────────────────────
const sec = (ms: number) => (ms / 1000).toFixed(3);

/** Crop window (w,h,x,y) that frames `zoom` inside a W×H canvas, clamped in-bounds. */
const cropBox = (zoom: Zoom) => {
  const cw = W / zoom.scale;
  const ch = H / zoom.scale;
  const cx = Math.min(Math.max(zoom.x - cw / 2, 0), W - cw);
  const cy = Math.min(Math.max(zoom.y - ch / 2, 0), H - ch);
  return {
    cw: Math.round(cw),
    ch: Math.round(ch),
    cx: Math.round(cx),
    cy: Math.round(cy),
  };
};

// Playwright's capture reports a non-1:1 SAR even though the encoded frame is
// already 1280x800; concat refuses to join segments whose SAR disagrees, so
// every chain normalizes it explicitly rather than relying on scale's default.
const NORMALIZE = "format=yuv420p,setsar=1";

/** Untouched footage — no crop, no zoom. */
const passthrough = (label: string, startMs: number, endMs: number) =>
  `[0:v]trim=start=${sec(startMs)}:end=${sec(endMs)},setpts=PTS-STARTPTS,${NORMALIZE}[${label}]`;

/** A constant-scale reframe: cut straight into position and hold. */
const staticZoom = (
  label: string,
  startMs: number,
  endMs: number,
  zoom: Zoom,
) => {
  const { cw, ch, cx, cy } = cropBox(zoom);
  return (
    `[0:v]trim=start=${sec(startMs)}:end=${sec(endMs)},setpts=PTS-STARTPTS,` +
    `crop=w=${cw}:h=${ch}:x=${cx}:y=${cy},scale=${W}:${H},${NORMALIZE}[${label}]`
  );
};

/** The one animated punch-in: ramps 1.0 -> target over ~0.6s, then holds. Real
 * per-frame zoom (not a still-image Ken Burns), so it needs zoompan (crop's
 * w/h only evaluate once — no good for a scale that changes over time) with
 * d=1 so it consumes exactly one input frame per output frame. */
const RAMP_FRAMES = 15;
const rampedZoom = (
  label: string,
  startMs: number,
  endMs: number,
  zoom: Zoom,
) => {
  const perFrame = (zoom.scale - 1) / RAMP_FRAMES;
  const z = `min(1+${perFrame.toFixed(5)}*on\\,${zoom.scale})`;
  const x = `max(0\\,min(${zoom.x}-(iw/zoom/2)\\,iw-iw/zoom))`;
  const y = `max(0\\,min(${zoom.y}-(ih/zoom/2)\\,ih-ih/zoom))`;
  return (
    `[0:v]trim=start=${sec(startMs)}:end=${sec(endMs)},setpts=PTS-STARTPTS,` +
    `zoompan=z='${z}':x='${x}':y='${y}':d=1:s=${W}x${H}:fps=${FPS},${NORMALIZE}[${label}]`
  );
};

// The freeze-hold: a still frame looped for freezeMs. tpad's stop_mode=clone
// was tried first and rejected — it silently cloned the wrong frame (verified
// by isolating trim+tpad+concat down to a minimal repro), while looping an
// extracted still via -loop 1 is the standard, reliable ffmpeg idiom for
// holding a frame. The still is cropped/zoomed identically to vE so the hold
// reads as a continuation of it, not a cut.
const agentCropBox = cropBox(agent.zoom);
const freezeSourcePng = `${outDir}freeze-source.png`;
const freezeHoldMp4 = `${outDir}freeze-hold.mp4`;

const videoChains = [
  passthrough("vA", 0, inlineEdit.startMs), // zero-chrome + intent lead-in
  rampedZoom("vB", inlineEdit.startMs, propSheet.startMs, inlineEdit.zoom),
  staticZoom("vC", propSheet.startMs, morph.startMs, propSheet.zoom),
  staticZoom("vD", morph.startMs, agent.startMs, morph.zoom),
  staticZoom("vE", agent.startMs, AGENT_CARD_GONE_SEC * 1000, agent.zoom),
  `[1:v]${NORMALIZE}[vFreeze]`,
  passthrough("vF", AGENT_CARD_GONE_SEC * 1000, videoDurationMs), // undo + outro
];
const videoGraph = [
  ...videoChains,
  `[vA][vB][vC][vD][vE][vFreeze][vF]concat=n=7:v=1:a=0[vout]`,
].join(";\n");

// ── Audio graph ───────────────────────────────────────────────────────
// Every beat's narration starts at its recorded start time; beats at or
// after the freeze seam shift later by the freeze-hold duration.
const narrationStartMs = (m: Mark) =>
  m.startMs + (m.startMs >= freezeInsertMs ? freezeMs : 0);

const beatOrder = [
  zeroChrome,
  intent,
  inlineEdit,
  propSheet,
  morph,
  agent,
  undo,
  outro,
];
const narrationInputs = beatOrder.flatMap((m) => [
  "-i",
  `${narrationDir}${m.id}.wav`,
]);
const audioChains = beatOrder.map(
  (m, i) =>
    `[${i}:a]adelay=delays=${Math.round(narrationStartMs(m))}:all=1[a${i}]`,
);
const audioGraph = [
  ...audioChains,
  `${beatOrder.map((_, i) => `[a${i}]`).join("")}amix=inputs=${beatOrder.length}:duration=longest:normalize=0[aout]`,
].join(";\n");

// ── Render ──────────────────────────────────────────────────────────────
const videoOut = `${outDir}compose-video.mp4`;
const audioOut = `${outDir}narration-mix.wav`;
const finalOut = `${outDir}duck-demo.mp4`;

console.log("[compose] extracting freeze-hold source frame…");
await run([
  "ffmpeg",
  "-y",
  "-v",
  "error",
  "-i",
  beatsFile.videoPath,
  "-ss",
  (AGENT_CARD_GONE_SEC - 0.05).toFixed(3), // margin before the verified cut
  "-frames:v",
  "1",
  "-vf",
  `crop=w=${agentCropBox.cw}:h=${agentCropBox.ch}:x=${agentCropBox.cx}:y=${agentCropBox.cy},scale=${W}:${H}`,
  freezeSourcePng,
]);

console.log("[compose] building freeze-hold clip…");
await run([
  "ffmpeg",
  "-y",
  "-v",
  "error",
  "-loop",
  "1",
  "-i",
  freezeSourcePng,
  "-t",
  (freezeMs / 1000).toFixed(3),
  "-r",
  String(FPS),
  "-vf",
  NORMALIZE,
  "-c:v",
  "libx264",
  "-pix_fmt",
  "yuv420p",
  "-crf",
  "17",
  "-preset",
  "medium",
  freezeHoldMp4,
]);

console.log("[compose] rendering video (punch-ins + freeze-hold)…");
await run([
  "ffmpeg",
  "-y",
  "-v",
  "error",
  "-i",
  beatsFile.videoPath,
  "-i",
  freezeHoldMp4,
  "-filter_complex",
  videoGraph,
  "-map",
  "[vout]",
  "-r",
  String(FPS),
  "-c:v",
  "libx264",
  "-pix_fmt",
  "yuv420p",
  "-crf",
  "17",
  "-preset",
  "medium",
  videoOut,
]);

console.log("[compose] mixing narration…");
await run([
  "ffmpeg",
  "-y",
  "-v",
  "error",
  ...narrationInputs,
  "-filter_complex",
  audioGraph,
  "-map",
  "[aout]",
  "-ar",
  "48000",
  audioOut,
]);

console.log("[compose] muxing final…");
await run([
  "ffmpeg",
  "-y",
  "-v",
  "error",
  "-i",
  videoOut,
  "-i",
  audioOut,
  "-c:v",
  "copy",
  "-c:a",
  "aac",
  "-b:a",
  "192k",
  "-ac",
  "2",
  "-movflags",
  "+faststart",
  finalOut,
]);

console.log(`[done] ${finalOut}`);
